env:
 browser: true
 es6: true
 node: true
extends: 'eslint:recommended'
rules:
  	
 no-catch-shadow: error
 yoda: error
 prefer-promise-reject-errors: error
 no-useless-call: error
 no-new: error
 no-new-func: error
 no-proto: error
 no-implied-eval: error
 no-alert: error
 no-caller: error
 no-eval: error
 require-jsdoc: ["error", {
                        "require": {
                            "FunctionDeclaration": true,
                            "MethodDefinition": true,
                            "ClassDeclaration": true,
                            "ArrowFunctionExpression": false
                        }
                    }]
 no-console: off
 array-bracket-spacing: error
 arrow-parens: [error, as-needed]
 comma-dangle: [error, never]
 complexity: error
 indent: [error, 4, {SwitchCase: 1}]
 linebreak-style: [error, unix]
 no-negated-condition: error
 no-nested-ternary: error
 no-plusplus: [error, {allowForLoopAfterthoughts: true}]
 no-shadow: error
 no-trailing-spaces: [error, {skipBlankLines: true}]
 no-unneeded-ternary: [error, {defaultAssignment: false}]
 no-var: error
 object-shorthand: [error, always]
 quotes: [error, single]
 semi: [error, always]
 arrow-spacing: error
 no-useless-constructor: error
 no-compare-neg-zero: error
 array-callback-return: error
 default-case: error	
 no-implicit-globals: error
 no-throw-literal: error	
 callback-return: error
 consistent-this: [error, _self]
 no-case-declarations: off
 